---
- name: Check if neovim is already installed
  ansible.builtin.shell: command -v nvim
  register: nvim_which
  changed_when: false
  failed_when: false

- name: Install neovim (Arch)
  become: true
  community.general.pacman:
    name: neovim
    state: present
  when:
    - ansible_facts['os_family'] == "Archlinux"
    - nvim_which.rc != 0

- name: Install neovim via Homebrew (macOS)
  community.general.homebrew:
    name: neovim
    state: present
  when: ansible_facts['os_family'] == "Darwin"
